export const data = [
	{
		Id: 15482,
		Line: 'Eccles',
		TLAREF: 'CNK',
		PIDREF: 'CNK-TPTD01',
		StationLocation: 'Cornbrook',
		AtcoCode: '9400ZZMACRN1',
		Direction: 'Incoming',
		Dest0: 'Piccadilly',
		Carriages0: 'Double',
		Status0: 'Departing',
		Wait0: '0',
		Dest1: 'Ashton-under-Lyne',
		Carriages1: 'Single',
		Status1: 'Due',
		Wait1: '3',
		Dest2: 'Deansgate Castlefield',
		Carriages2: 'Double',
		Status2: 'Due',
		Wait2: '5',
		Dest3: '',
		Carriages3: '',
		Status3: '',
		MessageBoard:
			'Today Manchester United welcome Leeds United to Old Trafford. Kick off is 20:00hrs and services are expected to be busier than usual. Please allow extra time for travel',
		Wait3: '',
		LastUpdated: '2023-02-08T22:38:16Z',
	},
	{
		Id: 15483,
		Line: 'Eccles',
		TLAREF: 'CNK',
		PIDREF: 'CNK-TPTD02',
		StationLocation: 'Cornbrook',
		AtcoCode: '9400ZZMACRN1',
		Direction: 'Incoming',
		Dest0: 'Piccadilly',
		Carriages0: 'Double',
		Status0: 'Departing',
		Wait0: '0',
		Dest1: 'Ashton-under-Lyne',
		Carriages1: 'Single',
		Status1: 'Due',
		Wait1: '3',
		Dest2: 'Deansgate Castlefield',
		Carriages2: 'Double',
		Status2: 'Due',
		Wait2: '5',
		Dest3: '',
		Carriages3: '',
		Status3: '',
		MessageBoard:
			'Today Manchester United welcome Leeds United to Old Trafford. Kick off is 20:00hrs and services are expected to be busier than usual. Please allow extra time for travel',
		Wait3: '',
		LastUpdated: '2023-02-08T22:38:16Z',
	},
	{
		Id: 15484,
		Line: 'Eccles',
		TLAREF: 'CNK',
		PIDREF: 'CNK-TPTD03',
		StationLocation: 'Cornbrook',
		AtcoCode: '9400ZZMACRN2',
		Direction: 'Outgoing',
		Dest0: 'East Didsbury',
		Carriages0: 'Double',
		Status0: 'Due',
		Wait0: '1',
		Dest1: 'Eccles via MediaCityUK',
		Carriages1: 'Single',
		Status1: 'Due',
		Wait1: '2',
		Dest2: 'Altrincham',
		Carriages2: 'Double',
		Status2: 'Due',
		Wait2: '4',
		Dest3: '',
		Carriages3: '',
		Status3: '',
		MessageBoard:
			'Today Manchester United welcome Leeds United to Old Trafford. Kick off is 20:00hrs and services are expected to be busier than usual. Please allow extra time for travel',
		Wait3: '',
		LastUpdated: '2023-02-08T22:38:16Z',
	},
	{
		Id: 15485,
		Line: 'Eccles',
		TLAREF: 'CNK',
		PIDREF: 'CNK-TPTD04',
		StationLocation: 'Cornbrook',
		AtcoCode: '9400ZZMACRN2',
		Direction: 'Outgoing',
		Dest0: 'East Didsbury',
		Carriages0: 'Double',
		Status0: 'Due',
		Wait0: '1',
		Dest1: 'Eccles via MediaCityUK',
		Carriages1: 'Single',
		Status1: 'Due',
		Wait1: '2',
		Dest2: 'Altrincham',
		Carriages2: 'Double',
		Status2: 'Due',
		Wait2: '4',
		Dest3: '',
		Carriages3: '',
		Status3: '',
		MessageBoard:
			'Today Manchester United welcome Leeds United to Old Trafford. Kick off is 20:00hrs and services are expected to be busier than usual. Please allow extra time for travel',
		Wait3: '',
		LastUpdated: '2023-02-08T22:38:16Z',
	},
];
